name: ChangeDamage
version: 1.0.0
description: Change damage done by an item
author: FalseVacuum
authors: [FalseVacuum] 
website: http://dev.bukkit.org/server-mods/changedamage/

main: vacuum.changedamage.ChangeDamage
database: false
depend: []

commands:
  changedamage:
    description: Access changedamage commands
    permission: vacuum.changedamage
    usage: |
      /<command> [[release][reload]]
      Example: /<command> reload - Reload the plugin
      Example: /<command> release - Disable the plugin
  
permissions:
  vacuum.changedamage:
    description: Access ChangeDamage commands
    default: op